[rocks]

[config]
plugins_dir = "plugins/"
auto_setup = true
colorscheme = "github_dark_default"

[treesitter]
auto_highlight = "all"

[bundles.mini]
items = [
  "mini.jump2d",
  "mini.surround",
  "mini.pairs",
  "mini.ai",
  "mini.comment"
]

[plugins]
"rocks.nvim" = "2.43.1"
"rocks-git.nvim" = "2.5.2"
"rocks-config.nvim" = "3.1.0"
"rocks-treesitter.nvim" = "1.3.0"
github-nvim-theme = "1.1.2"
"which-key.nvim" = "3.16.0"
"mason.nvim" = "1.11.0"
"mason-lspconfig.nvim" = "1.31.0"
tree-sitter-toml = "0.0.31"
"mini.jump2d" = "0.15.0"
"mini.surround" = "0.15.0"
"mini.pairs" = "0.15.0"
"mini.ai" = "0.15.0"
"mini.comment" = "0.15.0"
rustaceanvim = "5.24.4"
"render-markdown.nvim" = "8.0.0"
tree-sitter-python = "0.0.40"

[plugins.nvim-web-devicons]
git = "nvim-tree/nvim-web-devicons"
rev = "v0.100"

[plugins."snacks.nvim"]
git = "folke/snacks.nvim"
rev = "v2.20.0"

[plugins."lualine.nvim"]
git = "nvim-lualine/lualine.nvim"
rev = "f4f791f67e70d378a754d02da068231d2352e5bc"
config = { options = { theme = "horizon" } }

[plugins."oil.nvim"]
git = "stevearc/oil.nvim"
rev = "v2.14.0"
config = "plugins.oil"

[plugins.nvim-lspconfig]
version = "1.6.0"
config = false

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "efff286dd74c22f731cdec26a70b46e5b203c619"

[plugins.luasnip]
git = "l3mon4d3/luasnip"
rev = "v2.3.0"

[plugins."blink.compat"]
git = "saghen/blink.compat"
rev = "v2.4.0"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v0.11.0"

[plugins."blink.cmp".config]
keymap = { preset = 'enter' }
snippets = { preset = 'luasnip' }
sources = { default = [ 'lsp', 'path', 'snippets', 'buffer' ]  }
completion = { list = { selection = { preselect = false, auto_insert = false } } }

